# Site settings
title: jonchar
email: jonchar@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Home of jonchar.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jonchar.github.io" # the base hostname & protocol for your site
github_username:  jonchar

# Build settings
markdown: kramdown
